version: '3.8'

services:
  app:
    build:
      context: ./app
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  httpd:
    image: httpd:latest
    ports:
      - "8081:80"
    depends_on:
      - app

networks:
  default:
    driver: bridge
